name: Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "preview/**"
      - "styles/**"
      - "package.json"
      - "bun.lock"
      - "bunfig.toml"
      - ".github/workflows/pages.yml"

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      pages: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version-file: package.json

      - run: bun install --frozen-lockfile
      - run: bun run preview:build

      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v4.0.0
        with:
          path: dist/preview

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@ec21be9a1a72c8c69f2e14f7370269a8e7299df8 # v4.0.5
